"""initial schema: every collection of the former in-memory store, plus the
append-only guard on audit_events

Revision ID: 0001
Revises:
Create Date: 2026-10-07 18:16:34.262491
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('substance', sa.Text(), nullable=True),
    sa.Column('reaction', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('contrast', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_allergies_seq', 'allergies', ['seq'], unique=False)
    op.create_table('app_meta',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('appointments',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('referrer_id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('scanner_id', sa.Text(), nullable=True),
    sa.Column('exam_code', sa.Text(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('urgency', sa.Text(), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_confirmed', sa.Boolean(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('no_show_risk', sa.Float(), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_reminder', sa.Boolean(), nullable=True),
    sa.Column('requisition_id', sa.Text(), nullable=True),
    sa.Column('protocol_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_seq', 'appointments', ['seq'], unique=False)
    op.create_index('ix_appointments_start', 'appointments', ['start'], unique=False)
    op.create_table('audit_events',
    sa.Column('seq', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('source_ip', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.Text(), nullable=False),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('auth_sessions',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('backfill_cases',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source_appointment_id', sa.Text(), nullable=True),
    sa.Column('slot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('offers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('new_appointment_id', sa.Text(), nullable=True),
    sa.Column('filled_by_patient_id', sa.Text(), nullable=True),
    sa.Column('compute_ms', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_backfill_cases_seq', 'backfill_cases', ['seq'], unique=False)
    op.create_table('billing_work',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_billing_work_seq', 'billing_work', ['seq'], unique=False)
    op.create_table('calls',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('agent_mode', sa.Text(), nullable=True),
    sa.Column('verified_patient_id', sa.Text(), nullable=True),
    sa.Column('failed_verifications', sa.BigInteger(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('latencies_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_calls_seq', 'calls', ['seq'], unique=False)
    op.create_table('claims',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('payer', sa.Text(), nullable=True),
    sa.Column('fee_code', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('service_date', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_claims_seq', 'claims', ['seq'], unique=False)
    op.create_table('critical_cases',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Text(), nullable=True),
    sa.Column('study_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('referrer_id', sa.Text(), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('opened_by', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('step', sa.BigInteger(), nullable=True),
    sa.Column('next_action_at', sa.DateTime(), nullable=True),
    sa.Column('ack_due_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledgement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.Text(), nullable=True),
    sa.Column('close_note', sa.Text(), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_critical_cases_seq', 'critical_cases', ['seq'], unique=False)
    op.create_index('ix_critical_cases_status_next_action_at', 'critical_cases', ['status', 'next_action_at'], unique=False)
    op.create_table('dose_records',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('study_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('scanner_id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('exam_code', sa.Text(), nullable=True),
    sa.Column('protocol_id', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('sr_template', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ctdivol_mgy', sa.Float(), nullable=True),
    sa.Column('dlp_total_mgycm', sa.Float(), nullable=True),
    sa.Column('review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_dose_records_seq', 'dose_records', ['seq'], unique=False)
    op.create_table('dose_references',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ctdivol_mgy', sa.Float(), nullable=True),
    sa.Column('dlp_mgycm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_dose_references_seq', 'dose_references', ['seq'], unique=False)
    op.create_table('exams',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('modality', sa.Text(), nullable=True),
    sa.Column('minutes', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('prep_hours', sa.BigInteger(), nullable=True),
    sa.Column('contrast', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_exams_seq', 'exams', ['seq'], unique=False)
    op.create_table('extractions',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('requisition_id', sa.Text(), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_status', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('low_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_extractions_seq', 'extractions', ['seq'], unique=False)
    op.create_table('feedback_alerts',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('response_id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('followed_up_by', sa.Text(), nullable=True),
    sa.Column('followed_up_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_feedback_alerts_seq', 'feedback_alerts', ['seq'], unique=False)
    op.create_table('feedback_responses',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('survey_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('exam_code', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('rating', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('ai_status', sa.Text(), nullable=True),
    sa.Column('ai_sentiment', sa.Text(), nullable=True),
    sa.Column('ai_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_feedback_responses_seq', 'feedback_responses', ['seq'], unique=False)
    op.create_table('feedback_surveys',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('exam_code', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_feedback_surveys_seq', 'feedback_surveys', ['seq'], unique=False)
    op.create_table('images',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_table('inspection_documents',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('scanner_id', sa.Text(), nullable=True),
    sa.Column('staff_id', sa.Text(), nullable=True),
    sa.Column('performed', sa.Date(), nullable=True),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_inspection_documents_seq', 'inspection_documents', ['seq'], unique=False)
    op.create_table('inventory_items',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('product_code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('reorder_point', sa.BigInteger(), nullable=True),
    sa.Column('reorder_qty', sa.BigInteger(), nullable=True),
    sa.Column('lots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_inventory_items_seq', 'inventory_items', ['seq'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('item_id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('lot', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('by', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('inventory_orders',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('item_id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('supplier', sa.Text(), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_inventory_orders_seq', 'inventory_orders', ['seq'], unique=False)
    op.create_table('labs',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_labs_seq', 'labs', ['seq'], unique=False)
    op.create_table('llm_calls',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('module_state',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('mri_screenings',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('requisition_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('requisition_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('devices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_status', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('review_decision', sa.Text(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_mri_screenings_seq', 'mri_screenings', ['seq'], unique=False)
    op.create_table('offers',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Text(), nullable=True),
    sa.Column('waitlist_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('patient_name', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_offers_seq', 'offers', ['seq'], unique=False)
    op.create_table('outbox',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('to', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_outbox_seq', 'outbox', ['seq'], unique=False)
    op.create_index('ix_outbox_status_scheduled_for', 'outbox', ['status', 'scheduled_for'], unique=False)
    op.create_table('patients',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('given_name', sa.Text(), nullable=True),
    sa.Column('family_name', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('health_card', sa.Text(), nullable=True),
    sa.Column('health_card_version', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.Text(), nullable=True),
    sa.Column('dob_bidx', sa.Text(), nullable=True),
    sa.Column('health_card_bidx', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_patients_dob_bidx', 'patients', ['dob_bidx'], unique=False)
    op.create_index('ix_patients_health_card_bidx', 'patients', ['health_card_bidx'], unique=False)
    op.create_index('ix_patients_seq', 'patients', ['seq'], unique=False)
    op.create_table('peer_reviews',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Text(), nullable=True),
    sa.Column('study_id', sa.Text(), nullable=True),
    sa.Column('original_reader_id', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('score', sa.Text(), nullable=True),
    sa.Column('discrepancy_type', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_peer_reviews_seq', 'peer_reviews', ['seq'], unique=False)
    op.create_table('phipa_investigations',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('alert_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('assignee', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('trail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_phipa_investigations_seq', 'phipa_investigations', ['seq'], unique=False)
    op.create_table('prep_templates',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('english', sa.Text(), nullable=True),
    sa.Column('english_approved_by', sa.Text(), nullable=True),
    sa.Column('exam_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_prep_templates_seq', 'prep_templates', ['seq'], unique=False)
    op.create_table('prereg',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.Text(), nullable=True),
    sa.Column('insurance_type', sa.Text(), nullable=True),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_prereg_seq', 'prereg', ['seq'], unique=False)
    op.create_table('protocols',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('requisition_id', sa.Text(), nullable=True),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_id', sa.Text(), nullable=True),
    sa.Column('alternative_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('contrast_required', sa.Boolean(), nullable=True),
    sa.Column('ai_status', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('approved_id', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('suggested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_protocols_seq', 'protocols', ['seq'], unique=False)
    op.create_table('qa_runs',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('by', sa.Text(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('candidates', sa.BigInteger(), nullable=True),
    sa.Column('sampled', sa.BigInteger(), nullable=True),
    sa.Column('assigned', sa.BigInteger(), nullable=True),
    sa.Column('unassigned', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('reading_assignments',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('study_id', sa.Text(), nullable=True),
    sa.Column('radiologist_id', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Text(), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_reading_assignments_seq', 'reading_assignments', ['seq'], unique=False)
    op.create_table('referral_summaries',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('week_start', sa.Text(), nullable=True),
    sa.Column('headline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('ai_status', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_referral_summaries_seq', 'referral_summaries', ['seq'], unique=False)
    op.create_table('referral_visits',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('referrer_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('by', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_referral_visits_seq', 'referral_visits', ['seq'], unique=False)
    op.create_table('referrers',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('clinic', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('fax', sa.Text(), nullable=True),
    sa.Column('is_key', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_referrers_seq', 'referrers', ['seq'], unique=False)
    op.create_table('reports',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('study_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('referrer_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('ai_status', sa.Text(), nullable=True),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('image_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('urgent_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('llm_mode', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('signed_by', sa.Text(), nullable=True),
    sa.Column('signed_by_id', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('edit_ratio', sa.Float(), nullable=True),
    sa.Column('sent_to_referrer_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_reports_seq', 'reports', ['seq'], unique=False)
    op.create_table('requisitions',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('referrer_id', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('waitlist_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_requisitions_seq', 'requisitions', ['seq'], unique=False)
    op.create_table('retrieval_tasks',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('requisition_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('facility', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('attempts', sa.BigInteger(), nullable=True),
    sa.Column('max_attempts', sa.BigInteger(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_study_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_retrieval_tasks_seq', 'retrieval_tasks', ['seq'], unique=False)
    op.create_index('ix_retrieval_tasks_status_next_attempt_at', 'retrieval_tasks', ['status', 'next_attempt_at'], unique=False)
    op.create_table('scanners',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('modality', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('slot_minutes', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_scanners_seq', 'scanners', ['seq'], unique=False)
    op.create_table('sites',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('open_hour', sa.BigInteger(), nullable=True),
    sa.Column('close_hour', sa.BigInteger(), nullable=True),
    sa.Column('open_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modalities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('x_km', sa.Float(), nullable=True),
    sa.Column('y_km', sa.Float(), nullable=True),
    sa.Column('parking', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_sites_seq', 'sites', ['seq'], unique=False)
    op.create_table('staff',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('site_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('referrer_id', sa.Text(), nullable=True),
    sa.Column('reading_modalities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('demo_login', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_staff_seq', 'staff', ['seq'], unique=False)
    op.create_table('studies',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('referrer_id', sa.Text(), nullable=True),
    sa.Column('exam_code', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('study_uid', sa.Text(), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('source_facility', sa.Text(), nullable=True),
    sa.Column('prior_for_appointment_id', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('scanner_id', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('protocol_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_studies_seq', 'studies', ['seq'], unique=False)
    op.create_table('triage',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('requisition_id', sa.Text(), nullable=True),
    sa.Column('ai_priority', sa.Text(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('ai_red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_status', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('final_priority', sa.Text(), nullable=True),
    sa.Column('review_action', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('triaged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_triage_seq', 'triage', ['seq'], unique=False)
    op.create_table('waitlist',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Text(), nullable=True),
    sa.Column('referrer_id', sa.Text(), nullable=True),
    sa.Column('exam_code', sa.Text(), nullable=True),
    sa.Column('urgency', sa.Text(), nullable=True),
    sa.Column('acceptable_site_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('earliest_date', sa.Date(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('requisition_id', sa.Text(), nullable=True),
    sa.Column('protocol_id', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_waitlist_seq', 'waitlist', ['seq'], unique=False)
    # ### end Alembic commands ###

    # The audit log is append-only in the database too: rows can be added, never
    # changed or removed (a demo reset empties it with TRUNCATE, like every table).
    op.execute("""
        CREATE FUNCTION audit_events_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only (% refused)', TG_OP;
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER audit_events_append_only BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION audit_events_append_only();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit_events_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_seq', table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_index('ix_triage_seq', table_name='triage')
    op.drop_table('triage')
    op.drop_index('ix_studies_seq', table_name='studies')
    op.drop_table('studies')
    op.drop_index('ix_staff_seq', table_name='staff')
    op.drop_table('staff')
    op.drop_index('ix_sites_seq', table_name='sites')
    op.drop_table('sites')
    op.drop_index('ix_scanners_seq', table_name='scanners')
    op.drop_table('scanners')
    op.drop_index('ix_retrieval_tasks_status_next_attempt_at', table_name='retrieval_tasks')
    op.drop_index('ix_retrieval_tasks_seq', table_name='retrieval_tasks')
    op.drop_table('retrieval_tasks')
    op.drop_index('ix_requisitions_seq', table_name='requisitions')
    op.drop_table('requisitions')
    op.drop_index('ix_reports_seq', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_referrers_seq', table_name='referrers')
    op.drop_table('referrers')
    op.drop_index('ix_referral_visits_seq', table_name='referral_visits')
    op.drop_table('referral_visits')
    op.drop_index('ix_referral_summaries_seq', table_name='referral_summaries')
    op.drop_table('referral_summaries')
    op.drop_index('ix_reading_assignments_seq', table_name='reading_assignments')
    op.drop_table('reading_assignments')
    op.drop_table('qa_runs')
    op.drop_index('ix_protocols_seq', table_name='protocols')
    op.drop_table('protocols')
    op.drop_index('ix_prereg_seq', table_name='prereg')
    op.drop_table('prereg')
    op.drop_index('ix_prep_templates_seq', table_name='prep_templates')
    op.drop_table('prep_templates')
    op.drop_index('ix_phipa_investigations_seq', table_name='phipa_investigations')
    op.drop_table('phipa_investigations')
    op.drop_index('ix_peer_reviews_seq', table_name='peer_reviews')
    op.drop_table('peer_reviews')
    op.drop_index('ix_patients_seq', table_name='patients')
    op.drop_index('ix_patients_health_card_bidx', table_name='patients')
    op.drop_index('ix_patients_dob_bidx', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_outbox_status_scheduled_for', table_name='outbox')
    op.drop_index('ix_outbox_seq', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('ix_offers_seq', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ix_mri_screenings_seq', table_name='mri_screenings')
    op.drop_table('mri_screenings')
    op.drop_table('module_state')
    op.drop_table('llm_calls')
    op.drop_index('ix_labs_seq', table_name='labs')
    op.drop_table('labs')
    op.drop_index('ix_inventory_orders_seq', table_name='inventory_orders')
    op.drop_table('inventory_orders')
    op.drop_table('inventory_movements')
    op.drop_index('ix_inventory_items_seq', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_inspection_documents_seq', table_name='inspection_documents')
    op.drop_table('inspection_documents')
    op.drop_table('images')
    op.drop_index('ix_feedback_surveys_seq', table_name='feedback_surveys')
    op.drop_table('feedback_surveys')
    op.drop_index('ix_feedback_responses_seq', table_name='feedback_responses')
    op.drop_table('feedback_responses')
    op.drop_index('ix_feedback_alerts_seq', table_name='feedback_alerts')
    op.drop_table('feedback_alerts')
    op.drop_index('ix_extractions_seq', table_name='extractions')
    op.drop_table('extractions')
    op.drop_index('ix_exams_seq', table_name='exams')
    op.drop_table('exams')
    op.drop_index('ix_dose_references_seq', table_name='dose_references')
    op.drop_table('dose_references')
    op.drop_index('ix_dose_records_seq', table_name='dose_records')
    op.drop_table('dose_records')
    op.drop_index('ix_critical_cases_status_next_action_at', table_name='critical_cases')
    op.drop_index('ix_critical_cases_seq', table_name='critical_cases')
    op.drop_table('critical_cases')
    op.drop_index('ix_claims_seq', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_calls_seq', table_name='calls')
    op.drop_table('calls')
    op.drop_index('ix_billing_work_seq', table_name='billing_work')
    op.drop_table('billing_work')
    op.drop_index('ix_backfill_cases_seq', table_name='backfill_cases')
    op.drop_table('backfill_cases')
    op.drop_table('auth_sessions')
    op.drop_table('audit_events')
    op.drop_index('ix_appointments_start', table_name='appointments')
    op.drop_index('ix_appointments_seq', table_name='appointments')
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('app_meta')
    op.drop_index('ix_allergies_seq', table_name='allergies')
    op.drop_table('allergies')
    # ### end Alembic commands ###
