"""hospital FHIR resources

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 13:48:26.371936
"""

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fhir_resources',
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('patient', sa.Text(), nullable=True),
    sa.Column('encounter', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('cls', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('mrn_bidx', sa.Text(), nullable=True),
    sa.Column('hcn_bidx', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('resource_type', 'id')
    )
    op.create_index('ix_fhir_date', 'fhir_resources', ['resource_type', 'date'], unique=False)
    op.create_index('ix_fhir_encounter', 'fhir_resources', ['resource_type', 'encounter'], unique=False)
    op.create_index('ix_fhir_mrn', 'fhir_resources', ['mrn_bidx'], unique=False)
    op.create_index('ix_fhir_patient', 'fhir_resources', ['resource_type', 'patient'], unique=False)
    op.create_index('ix_fhir_seq', 'fhir_resources', ['seq'], unique=False)
    op.create_index('ix_fhir_status', 'fhir_resources', ['resource_type', 'status'], unique=False)
    op.create_index('ix_fhir_unit', 'fhir_resources', ['resource_type', 'unit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fhir_unit', table_name='fhir_resources')
    op.drop_index('ix_fhir_status', table_name='fhir_resources')
    op.drop_index('ix_fhir_seq', table_name='fhir_resources')
    op.drop_index('ix_fhir_patient', table_name='fhir_resources')
    op.drop_index('ix_fhir_mrn', table_name='fhir_resources')
    op.drop_index('ix_fhir_encounter', table_name='fhir_resources')
    op.drop_index('ix_fhir_date', table_name='fhir_resources')
    op.drop_table('fhir_resources')
    # ### end Alembic commands ###
