"""integration dead letters

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 15:43:41.314413
"""

from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letters',
    sa.Column('row_key', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('adapter', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('row_key')
    )
    op.create_index('ix_dead_letters_adapter_status', 'dead_letters', ['adapter', 'status'], unique=False)
    op.create_index('ix_dead_letters_seq', 'dead_letters', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dead_letters_seq', table_name='dead_letters')
    op.drop_index('ix_dead_letters_adapter_status', table_name='dead_letters')
    op.drop_table('dead_letters')
    # ### end Alembic commands ###
