"""Additive Phase 1 bilingual terminology migration.

This module deliberately does not import the destructive KG rebuild pipeline and never
connects to Neo4j. It adds reviewed aliases to PostgreSQL and can optionally build a
separate multilingual Chroma collection. Re-running it is safe.
"""

import argparse
import hashlib
import json
from dataclasses import dataclass, replace
from pathlib import Path

import chromadb

from configuration import config
from datasync.entity_alignment import (
    LANGUAGE_EN,
    LANGUAGE_ZH,
    _connect,
    get_multilingual_embedding_model,
    init_db,
    normalize_alias,
)


SUPPORTED_SCHEMAS = {"disease", "symptom", "department", "drug"}
DEFAULT_FIXTURE_PATH = (
    config.ROOT_DIR / "data" / "terminology" / "bilingual_medical_sample.json"
)


@dataclass(frozen=True)
class AliasRecord:
    concept_id: str
    entity_schema: str
    alias: str
    language: str
    canonical_name: str
    source: str

    @property
    def normalized_alias(self) -> str:
        return normalize_alias(self.alias, self.language)


def canonical_entity_id(entity_schema: str, canonical_name: str) -> str:
    """Keep Phase 1 compatible with the IDs already generated by the project."""
    digest = hashlib.md5(canonical_name.encode()).hexdigest()[:16]
    return f"{entity_schema}_{digest}"


def load_terminology(path: Path = DEFAULT_FIXTURE_PATH) -> list[dict]:
    with open(path, "r", encoding="utf-8") as fixture_file:
        payload = json.load(fixture_file)
    if not isinstance(payload, list):
        raise ValueError("术语 fixture 顶层必须是 JSON 数组")
    return payload


def iter_alias_records(concepts: list[dict]):
    """Validate concepts and expand their zh/en alias arrays into mapping rows."""
    for concept in concepts:
        entity_schema = concept.get("entity_schema")
        canonical_name = (concept.get("canonical_name") or "").strip()
        source = (concept.get("source") or "phase1_sample").strip()
        if entity_schema not in SUPPORTED_SCHEMAS:
            raise ValueError(f"不支持的 entity_schema: {entity_schema}")
        if not canonical_name:
            raise ValueError("canonical_name 不能为空")
        concept_id = concept.get("id") or canonical_entity_id(
            entity_schema, canonical_name
        )

        aliases_by_language = {
            LANGUAGE_ZH: [canonical_name, *(concept.get("aliases_zh") or [])],
            LANGUAGE_EN: concept.get("aliases_en") or [],
        }
        seen = set()
        for language, aliases in aliases_by_language.items():
            for alias in aliases:
                alias = (alias or "").strip()
                if not alias:
                    continue
                normalized = normalize_alias(alias, language)
                dedupe_key = (language, normalized)
                if dedupe_key in seen:
                    continue
                seen.add(dedupe_key)
                yield AliasRecord(
                    concept_id=concept_id,
                    entity_schema=entity_schema,
                    alias=alias,
                    language=language,
                    canonical_name=canonical_name,
                    source=source,
                )


def _select_existing(cur, record: AliasRecord):
    cur.execute(
        "select id, std_name, is_reviewed from entity_mapping "
        "where synonym=%s and entity_schema=%s for update",
        (record.alias, record.entity_schema),
    )
    return cur.fetchone()


def _validate_existing_mapping(existing, record: AliasRecord):
    if (
        existing
        and existing["is_reviewed"] == 1
        and existing["std_name"] != record.canonical_name
    ):
        raise ValueError(
            "审核过的别名映射发生冲突: "
            f"{record.entity_schema}/{record.alias}: "
            f"{existing['std_name']} != {record.canonical_name}"
        )


def _validate_normalized_mapping(cur, record: AliasRecord):
    cur.execute(
        "select distinct std_name from entity_mapping "
        "where entity_schema=%s and language=%s and normalized_synonym=%s "
        "and is_reviewed=1",
        (record.entity_schema, record.language, record.normalized_alias),
    )
    conflicting_names = {
        row["std_name"]
        for row in cur.fetchall()
        if row["std_name"] != record.canonical_name
    }
    if conflicting_names:
        raise ValueError(
            "审核过的规范化别名映射发生冲突: "
            f"{record.entity_schema}/{record.normalized_alias}: "
            f"{sorted(conflicting_names)} != {record.canonical_name}"
        )


def _resolve_concept_ids(cur, records: list[AliasRecord]):
    """Reuse an existing reviewed concept ID; never silently rewrite concept identity."""
    records_by_concept = {}
    for record in records:
        key = (record.entity_schema, record.canonical_name)
        records_by_concept.setdefault(key, set()).add(record.concept_id)

    resolved = {}
    for (entity_schema, canonical_name), fixture_ids in records_by_concept.items():
        if len(fixture_ids) != 1:
            raise ValueError(
                f"fixture 为同一概念声明了多个 ID: {entity_schema}/{canonical_name}"
            )
        cur.execute(
            "select distinct id from entity_mapping "
            "where entity_schema=%s and std_name=%s and is_reviewed=1",
            (entity_schema, canonical_name),
        )
        existing_ids = {row["id"] for row in cur.fetchall()}
        if len(existing_ids) > 1:
            raise ValueError(
                "现有审核映射的概念 ID 不一致，拒绝自动改写: "
                f"{entity_schema}/{canonical_name}: {sorted(existing_ids)}"
            )
        resolved[(entity_schema, canonical_name)] = (
            existing_ids.pop() if existing_ids else next(iter(fixture_ids))
        )
    return resolved


def upsert_reviewed_aliases(
    records: list[AliasRecord],
) -> tuple[int, int, dict[tuple[str, str], str]]:
    """Insert/update fixture aliases without replacing conflicting reviewed mappings."""
    inserted = 0
    updated = 0
    with _connect() as conn:
        with conn.cursor() as cur:
            concept_ids = _resolve_concept_ids(cur, records)
            for record in records:
                concept_id = concept_ids[
                    (record.entity_schema, record.canonical_name)
                ]
                _validate_normalized_mapping(cur, record)
                existing = _select_existing(cur, record)
                _validate_existing_mapping(existing, record)
                if not existing:
                    cur.execute(
                        "insert into entity_mapping "
                        "(id, synonym, std_name, entity_schema, is_reviewed, language, "
                        "normalized_synonym, source, match_confidence) "
                        "values (%s, %s, %s, %s, 1, %s, %s, %s, 1.0) "
                        "on conflict do nothing",
                        (
                            concept_id,
                            record.alias,
                            record.canonical_name,
                            record.entity_schema,
                            record.language,
                            record.normalized_alias,
                            record.source,
                        ),
                    )
                    if cur.rowcount:
                        inserted += 1
                        continue
                    # A concurrent/idempotent insert won the race; validate it below.
                    existing = _select_existing(cur, record)
                    _validate_existing_mapping(existing, record)

                cur.execute(
                    "update entity_mapping set id=%s, std_name=%s, is_reviewed=1, "
                    "language=%s, normalized_synonym=%s, source=%s, "
                    "match_confidence=1.0, update_time=now() "
                    "where synonym=%s and entity_schema=%s and "
                    "(id, std_name, is_reviewed, language, normalized_synonym, "
                    "source, match_confidence) is distinct from "
                    "(%s, %s, 1, %s, %s, %s, 1.0)",
                    (
                        concept_id,
                        record.canonical_name,
                        record.language,
                        record.normalized_alias,
                        record.source,
                        record.alias,
                        record.entity_schema,
                        concept_id,
                        record.canonical_name,
                        record.language,
                        record.normalized_alias,
                        record.source,
                    ),
                )
                updated += cur.rowcount
        conn.commit()
    return inserted, updated, concept_ids


def index_multilingual_aliases(records: list[AliasRecord]) -> int:
    """Upsert reviewed aliases into an isolated multilingual vector collection."""
    if not config.MULTILINGUAL_EMBEDDING_MODEL_PATH:
        print("未配置 MULTILINGUAL_EMBEDDING_MODEL_PATH；已跳过多语种向量索引")
        return 0
    if not records:
        return 0

    config.validate_vector_collection_isolation()
    model = get_multilingual_embedding_model()
    documents = [record.alias for record in records]
    embeddings = model.encode(
        documents,
        batch_size=64,
        show_progress_bar=True,
        normalize_embeddings=True,
    )
    ids = [
        f"{record.concept_id}_{record.language}_"
        f"{hashlib.md5(record.normalized_alias.encode()).hexdigest()[:16]}"
        for record in records
    ]
    metadatas = [
        {
            "type": record.entity_schema,
            "language": record.language,
            "canonical_name": record.canonical_name,
            "concept_id": record.concept_id,
            "source": record.source,
            "reviewed": True,
        }
        for record in records
    ]

    client = chromadb.PersistentClient(path=str(config.VECTOR_STORE_DIR))
    collection = client.get_or_create_collection(
        config.MULTILINGUAL_VECTOR_COLLECTION,
        metadata={"hnsw:space": "cosine"},
    )
    collection.upsert(
        ids=ids,
        documents=documents,
        metadatas=metadatas,
        embeddings=embeddings,
    )
    return len(records)


def migrate_bilingual_terminology(
    fixture_path: Path = DEFAULT_FIXTURE_PATH, build_vector_index: bool = True
) -> dict[str, int]:
    """Run the additive, idempotent PostgreSQL/Chroma migration."""
    concepts = load_terminology(fixture_path)
    records = list(iter_alias_records(concepts))
    init_db()
    inserted, updated, concept_ids = upsert_reviewed_aliases(records)
    resolved_records = [
        replace(
            record,
            concept_id=concept_ids[(record.entity_schema, record.canonical_name)],
        )
        for record in records
    ]
    indexed = (
        index_multilingual_aliases(resolved_records) if build_vector_index else 0
    )
    return {
        "concepts": len(concepts),
        "aliases": len(records),
        "inserted": inserted,
        "updated": updated,
        "indexed": indexed,
    }


def main():
    parser = argparse.ArgumentParser(
        description="增量导入审核过的中英文医疗别名；不会修改 Neo4j"
    )
    parser.add_argument("--fixture", type=Path, default=DEFAULT_FIXTURE_PATH)
    parser.add_argument(
        "--skip-vector",
        action="store_true",
        help="只导入 PostgreSQL 确定性映射，不构建可选多语种向量索引",
    )
    args = parser.parse_args()
    result = migrate_bilingual_terminology(
        fixture_path=args.fixture,
        build_vector_index=not args.skip_vector,
    )
    print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
