"""Dictated reports: studies read without an AI draft (every modality other than
the chest X-ray drafting flow). Templates are fixed normal-report wording the
radiologist edits; nothing here is generated by a model."""

from datetime import datetime

from app.core.models import ImagingStudy
from app.core.store import Store
from app.modules.reports.service import Report, Section, report_for_study, save

# exam code -> (findings, impression) for a normal study
NORMAL_TEXT: dict[str, tuple[str, str]] = {
    "MR_BRAIN": ("No restricted diffusion, mass effect or abnormal enhancement. Ventricles and sulci normal for age.",
                 "Normal MRI of the brain."),
    "MR_LSPINE": ("Normal alignment. Mild disc desiccation at L4-5 without canal or foraminal stenosis.",
                  "Mild degenerative disc change at L4-5. No neural compromise."),
    "MR_KNEE": ("Menisci and cruciate ligaments intact. No bone marrow oedema. Small joint effusion.",
                "No internal derangement. Small effusion."),
    "CT_CHEST_C": ("No pulmonary embolism. No mass, consolidation or effusion. No lymphadenopathy.",
                   "No acute abnormality in the chest."),
    "CT_ABD_PEL": ("Solid organs unremarkable. No bowel obstruction, collection or free air. No lymphadenopathy.",
                   "No acute abnormality in the abdomen or pelvis."),
    "CT_HEAD": ("No intracranial haemorrhage, mass effect or territorial infarct. Ventricles normal.",
                "No acute intracranial abnormality."),
    "CT_CHEST": ("No suspicious pulmonary nodule. Mild centrilobular emphysema. No effusion.",
                 "Mild emphysema. No suspicious nodule."),
    "US_ABD": ("Liver normal in size and echotexture. No gallstones. Kidneys normal without hydronephrosis.",
               "Normal abdominal ultrasound."),
    "US_PELVIS": ("Uterus and ovaries normal in size and appearance. No free fluid.",
                  "Normal pelvic ultrasound."),
    "US_THYROID": ("Thyroid normal in size. Two sub-centimetre spongiform nodules (TI-RADS 1).",
                   "Benign-appearing thyroid nodules; no follow-up required."),
    "US_VENOUS": ("Normal compressibility and flow in the deep veins from the common femoral to the calf veins.",
                  "No deep vein thrombosis."),
    "XR_CHEST": ("Lungs clear. No effusion or pneumothorax. Heart size normal.",
                 "No acute cardiopulmonary abnormality."),
    "XR_KNEE": ("Mild medial joint space narrowing with small osteophytes. No fracture or effusion.",
                "Mild medial compartment osteoarthritis."),
    "XR_LSPINE": ("Normal alignment. Mild multilevel disc space narrowing. No fracture.",
                  "Mild lumbar spondylosis."),
}


def template(exam_code: str) -> tuple[str, str]:
    return NORMAL_TEXT.get(exam_code, ("", ""))


def sections(findings: str, impression: str) -> list[Section]:
    return [
        Section(key="findings", label="Findings", ai_text="", final_text=findings, status="edited"),
        Section(key="impression", label="Impression", ai_text="", final_text=impression, status="edited"),
    ]


def sign_dictated(store: Store, study: ImagingStudy, *, findings: str, impression: str, signer_id: str,
                  signer_name: str, signed_at: datetime | None = None) -> Report:
    """Create and sign a dictated report in one step (seeded history and the backlog board)."""
    signed_at = signed_at or datetime.now()
    existing = report_for_study(store, study.id)
    report = Report(
        id=existing.id if existing else store.next_id("RPT"), study_id=study.id, patient_id=study.patient_id,
        referrer_id=study.referrer_id, status="signed", source="dictated", sections=sections(findings, impression),
        created_at=signed_at, signed_by=signer_name, signed_by_id=signer_id, signed_at=signed_at,
    )
    save(store, report)
    return report
